### PR TITLE
add Linux sandbox workaround option

### PR DESCRIPTION
**Pull request by stardiviner**

### CODE REVIEW

**Comment by arnm** [comment]
Hey @stardiviner,

Thanks for the contribution! 

However, these changes seem to be very specific to your issue. I think a more general solution would be to be able to specify cli options as org-babel params like `file`/`-o` options is being used.

This would enable anyone to specify the cli options they need to pass along to `mmdc`. Though, it might get a little tedious to specify some options repeatedly in the org-babel syntax. Allowing for some way to specify defaults for cli options would be pretty useful.

**Comment by stardiviner** [comment]
Gentle ping .... @arnm

**Comment by arnm** [comment]
@stardiviner #1 has been implemented. closing this one. you can try creating another issue if you need

**Comment by stardiviner** [comment]
@arnm Thanks !

**Pull request closed without merging**
